"""
Django settings for agentserver project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+h@-*=zd47pkn3kc!y7(0l#nsprsxj2v6-2c#=v8r%t7uu*0o3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'funcapp.apps.FuncappConfig',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'agentserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agentserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        "OPTIONS": {
            "read_default_file": "agentserver/mysqldb.cnf",
        },
		"HOST": "hackathon-mysql-db.cz8gsi6e2ec6.ap-northeast-1.rds.amazonaws.com",
		"PORT": "3306"
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

# Agent properties.

PROMPT_TEMPLATE_SYSTEM_CHAT = 'You are going to assist the user to audit a transaction by client %s through email (message_id="%d"). Answer the user\'s question or follow the users instruction. The user is going to provide the details of the email, the attachment, the client.'

PROMPT_TEMPLATE_SYSTEM_AUDIT = 'Please audit a transaction from client %s through email (message_id="%d"). The user will provide the email content, attached transaction detail files and the client\'s profile as reference. If you consider the transaction valid, please set audit_pass as true and congratulate the client. Otherwise, please set audit_pass as false and tell the client the reason.Use tool "add_audit_judgement" to add your judgement to DB.'

ACCESSIBLE_ROOT = "D:\\hackathon_io\\outputs"

AGENT_SYSTEM_MESSAGE_MESSANGER = 'You are a messanger agent who reads emails and register them to DB.'
AGENT_TOOLS_MESSANGER = ['register_a_message']
AGENT_MODEL_MESSANGER = 'qwen-max'

AGENT_TOOLS_AUDITOR = [
            {'mcpServers': {  # You can specify the MCP configuration file
                "filesystem": {
                    "command": "npx",
                    "args": [
                        "-y",
                        "@modelcontextprotocol/server-filesystem",
                        ACCESSIBLE_ROOT
                    ]
                },
                "playwright": {
                    "command": "npx",
                    "args": [
                        "@playwright/mcp@latest"
                    ]
                }
            }
            },
            'add_audit_judgement'
        ]

AGENT_SYSTEM_MESSAGE_AUDITOR = '''
                    You are an AI auditor of stock transactions. 
                    Make judgements according to clients' documents, market rules and client profile.
                    1. Use Playwright to search for stock information from Google finance(https://www.google.com/finance/).
                    2. Use Filesystem to read the clients' documents.
                    3. Regulations will be provided as a context.
                    4. Make your decisions and write your judgement.
                    '''

AGENT_MODEL_AUDITOR = 'qwen3-next-80b-a3b-instruct'

AGENT_TOOLS_REVIEWER = ['add_audit_judgement']

AGENT_SYSTEM_MESSAGE_REVIEWER = 'You are a reviewer agent who reviews the judgement of the auditor. Check whether there are conflict across the judgement of different transaction emails.'

AGENT_MODEL_REVIEWER = 'qwen-max-latest'

AGENT_TOOLS_ASSISTANT_CHAT = [
            {'mcpServers': {  # You can specify the MCP configuration file
                "filesystem": {
                    "command": "npx",
                    "args": [
                        "-y",
                        "@modelcontextprotocol/server-filesystem",
                        ACCESSIBLE_ROOT
                    ]
                },
                "playwright": {
                    "command": "npx",
                    "args": [
                        "@playwright/mcp@latest"
                    ]
                }
            }
            },
            'get_target_message',
            'register_a_message',
            'add_audit_judgement'
        ]

AGENT_SYSTEM_MESSAGE_ASSISTANT_CHAT = '''
                    You are an AI auditor of stock transactions. 
                    Make judgements according to clients' documents, market rules and client profile.
                    1. Use Playwright to search for stock information from Google finance(https://www.google.com/finance/).
                    2. Use Filesystem to read the clients' documents.
                    3. Regulations will be provided as a context.
                    4. Make your decisions and write your judgement.
                    5. Reply the human auditor's doubts in chat.
                    '''

AGENT_MODEL_ASSISTANT_CHAT = 'qwen3-next-80b-a3b-instruct'