# Generated by Django 5.2.8 on 2025-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('audit_pass', models.BooleanField()),
                ('audit_judgement', models.TextField()),
            ],
        ),
    ]
