# Generated by Django 5.2.8 on 2025-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('profile', models.TextField()),
                ('total_asset_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('audit_pass', models.BooleanField()),
                ('audit_judgement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
