# Generated by Django 5.2.8 on 2025-11-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
