# Generated by Django 5.2.8 on 2025-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0002_rename_clients_client_rename_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_asset_value',
            field=models.FloatField(default=0.0),
        ),
    ]
